### PR TITLE
fix: update types to include tokenMap

### PR DESCRIPTION
**Pull request by lynnshaoyu**
This should've been done in https://github.com/Uniswap/token-lists/pull/420 , but overlooked this and updating the schemas in this PR.

### CODE REVIEW

**Review by cgkol — APPROVED** [review]

**Review by Imebeez — COMMENTED** [review]
👍

**Review by Imebeez — COMMENTED** [review]
😬

**Review by alokeutpal — APPROVED** [review]

**Comment by sadgirl1011** [comment]
> This should've been done in https://github.com/Uniswap/token-lists/pull/420 , but overlooked this and updating the schemas in this PR.

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Imebeez — COMMENTED** [review]
[]()

**Comment by krud491** [comment]
Reviewed and approved

**Comment by noelportillo** [comment]
Hi

**Review by krud491 — APPROVED** [review]

**Review by Imebeez — COMMENTED** [review]
[]()

**Pull request merged**
