### PR TITLE
chore: add provenance

### PR DESCRIPTION
**Pull request by mr-uniswap**
Adds npm provenance (since this repo is public)

### CODE REVIEW

**Review by matteenm — APPROVED** [review]

**Comment by beage666** [comment]
On

**Comment by beage666** [comment]
We're can I withdraw

**Review by Scutua — APPROVED** [review]

**Review by drewgitgit — COMMENTED** [review]
How to pull successfully

**Review by drewgitgit — COMMENTED** [review]
K

**Review by Imebeez — COMMENTED** [review]
@

**Pull request merged**
