### PR TITLE
stop using old versions of node.js

### PR DESCRIPTION
**Pull request by JFrankfurt**

### CODE REVIEW

**Review by Majidbaba — COMMENTED** [review]
Se

**Comment by moodysalem** [comment]
12 is technically not eol

**Comment by JFrankfurt** [comment]
I just noticed tsdx defaults include 10 not 16. Seemed worth keeping versions inline with current version best practice. This is not important.

**Comment by Mongkol67** [comment]
> _ No description provided. _

**Comment by Zionsammy** [comment]
Thanks

**Pull request closed without merging**
