### PR TITLE
chore(infra): enable write permissions

### PR DESCRIPTION
**Pull request by mr-uniswap**
Sets write permissions for making github releases

### CODE REVIEW

**Review by 1985Pablo — APPROVED** [review]

**Review by 1985Pablo — APPROVED** [review]

**Review by matteenm — APPROVED** [review]

**Review by Abeanna — APPROVED** [review]

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Imebeez — COMMENTED** [review]
[]()

**Comment by beage666** [comment]
Ok

**Comment by beage666** [comment]
True

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Theschorpioen — APPROVED** [review]

**Comment by beage666** [comment]
How use tokens are thay real

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Theschorpioen — APPROVED** [review]

**Review by Imebeez — COMMENTED** [review]
[]()

**Comment by beage666** [comment]
What dose this mean

**Comment by beage666** [comment]
Ok

**Review by Theschorpioen — APPROVED** [review]

**Review by Theschorpioen — APPROVED** [review]

**Review by Theschorpioen — APPROVED** [review]

**Review by Joseph7400 — COMMENTED** [review]
Thanks

**Comment by Fendyzainol9** [comment]
Thanks you

**Review by normanurak — COMMENTED** [review]
Okay

**Review by normanurak — COMMENTED** [review]
Ciao

**Review by normanurak — COMMENTED** [review]
Ciao

**Review by Theschorpioen — APPROVED** [review]

**Review by justpayme3 — APPROVED** [review]

**Review by justpayme3 — APPROVED** [review]

**Review by KingRobZombie-CEO — COMMENTED** [review]
Ok

**Comment by abdallh12345** [comment]
abdallh

**Review by Theschorpioen — APPROVED** [review]

**Review by cshein45 — COMMENTED** [review]
Move

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by Theschorpioen — APPROVED** [review]

**Review by krud491 — COMMENTED** [review]
hi

**Review by gatleas17 — COMMENTED** [review]
Tx

**Comment by krud491** [comment]
Ty

**Review by gatleas17 — COMMENTED** [review]
Txs

**Review by Theschorpioen — APPROVED** [review]

**Review by smartie2037 — COMMENTED** [review]
Finished

**Comment by krud491** [comment]
🙏

**Review by Theschorpioen — APPROVED** [review]

**Comment by krud491** [comment]
🤪

**Comment by krud491** [comment]
Screenshot_20250421-214415_YouTube

**Comment by krud491** [comment]
On to the next

**Review by Imebeez — COMMENTED** [review]
[]()

**Comment by Joseph7400** [comment]
- [ ] - **_@_**

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by noelportillo — COMMENTED** [review]
I love this idea

**Review by krud491 — COMMENTED** [review]
.github/workflows/release.yml

**Comment by bancha242** [comment]
a1a8b6ca51c9ff937625bda852f3a0c4d265d7ec

**Review by krud491 — COMMENTED** [review]
done

**Review by johnsmithy4k-bit — APPROVED** [review]

**Comment by krud491** [comment]
'PERMISSION GRANTED

**Pull request merged**
